### ISSUE TITLE
数据库长度不足

### ISSUE THREAD

**Issue by meimosor** [0x676e67/mayi#10]
当权限过多时，数据库会放不下，有没有什么解决办法？
![image](https://user-images.githubusercontent.com/31975932/174251504-a46c989d-7089-41ae-8afd-a6c04accb662.png)

**Comment by 0x676e67** [comment]
怎么会呢？报错看看

**Comment by meimosor** [comment]
我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决

**Comment by 0x676e67** [comment]
> 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决

这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了

**Comment by meimosor** [comment]
> > 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决
> 
> 这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了

主要是担心authorities太多，导致jwt payload放不下，而且生成的token也很长，前端也不好存。有没有更优雅的解决方案呢

**Comment by 0x676e67** [comment]
> > > 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决
> > 
> > 
> > 这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了
> 
> 主要是担心authorities太多，导致jwt payload放不下，而且生成的token也很长，前端也不好存。有没有更优雅的解决方案呢

一般只有数据库放不下（只能自己改长度，自己掂量），playload都可以放的，有一种解决方案是自己实现使用Redis一套存储方案，redis支持字符串足够长

**Comment by meimosor** [comment]
> > > > 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决
> > > 
> > > 
> > > 这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了
> > 
> > 
> > 主要是担心authorities太多，导致jwt payload放不下，而且生成的token也很长，前端也不好存。有没有更优雅的解决方案呢
> 
> 一般只有数据库放不下（只能自己改长度，自己掂量），playload都可以放的，有一种解决方案是自己实现使用Redis一套存储方案，redis支持字符串足够长

我想直接使用role来解决这个问题，以避免这个问题，不知道是否可行。因为role相对于resource少很多

**Comment by 0x676e67** [comment]
> > > > > 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决
> > > > 
> > > > 
> > > > 这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了
> > > 
> > > 
> > > 主要是担心authorities太多，导致jwt payload放不下，而且生成的token也很长，前端也不好存。有没有更优雅的解决方案呢
> > 
> > 
> > 一般只有数据库放不下（只能自己改长度，自己掂量），playload都可以放的，有一种解决方案是自己实现使用Redis一套存储方案，redis支持字符串足够长
> 
> 我想直接使用role来解决这个问题，以避免这个问题，不知道是否可行。因为role相对于resource少很多

也可以，只不过权限细粒度会大点，还有需要改动太多。相当于重构

**Comment by meimosor** [comment]
> > > > > > 我把oauth2_authorization的attributes字段改成blob字段可以了，不知道有没有其他办法解决
> > > > > 
> > > > > 
> > > > > 这个是长度限制，默认是用Spring Authorization 官方给的数据表，你可以把数据库字段长度改长一点就行了
> > > > 
> > > > 
> > > > 主要是担心authorities太多，导致jwt payload放不下，而且生成的token也很长，前端也不好存。有没有更优雅的解决方案呢
> > > 
> > > 
> > > 一般只有数据库放不下（只能自己改长度，自己掂量），playload都可以放的，有一种解决方案是自己实现使用Redis一套存储方案，redis支持字符串足够长
> > 
> > 
> > 我想直接使用role来解决这个问题，以避免这个问题，不知道是否可行。因为role相对于resource少很多
> 
> 也可以，只不过权限细粒度会大点，还有需要改动太多。相当于重构

好吧，谢谢解答，我先尝试下
