### ISSUE TITLE
接口签名问题

### ISSUE THREAD

**Issue by meimosor** [0x676e67/mayi#11]
如图，开启接口签名后，无法进入对应模式的断点。试了OPEN和SECRET下的单服务模式和网关模式都不行
![image](https://user-images.githubusercontent.com/31975932/196838447-6636d421-509f-4dde-b5ef-586e75a2e1d0.png)

**Comment by meimosor** [comment]
每个服务的签名配置如下：
api-encrypt:
  open: true
  show-log: true
auth:
  enable-signature: true
  model: false

**Comment by 0x676e67** [comment]
已经很久没写Java了，忘记了
