### ISSUE TITLE
可以加个使用说明吗？登录那块找不到是哪个接口

### ISSUE THREAD

**Issue by meimosor** [0x676e67/mayi#7]
可以加个使用说明吗？登录那块找不到是哪个接口

**Comment by 0x676e67** [comment]
> 可以加个使用说明吗？登录那块找不到是哪个接口

https://github.com/gngpp/mayi/blob/b417035aaa896a154092103699811eab2f4c12b3/mayi-auth/src/main/java/com/zf1976/mayi/auth/config/AuthorizationServerSecurityConfiguration.java#L283，看里面方法，这是oauth2.1版本

**Comment by 0x676e67** [comment]
https://github.com/gngpp/mayi/blob/b417035aaa896a154092103699811eab2f4c12b3/mayi-auth/src/main/java/com/zf1976/mayi/auth/config/AuthorizationServerSecurityConfiguration.java#L283


你需要查看Spring Authorization文档




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gngpp/mayi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午4:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gngpp/mayi] 可以加个使用说明吗？登录那块找不到是哪个接口 (Issue #7)





 
可以加个使用说明吗？登录那块找不到是哪个接口

**Comment by meimosor** [comment]
已解决
