### ISSUE TITLE
大佬，有几个问题请教下

### ISSUE THREAD

**Issue by meimosor** [0x676e67/mayi#8]
1、Context这个类如果要在集群下使用，有什么方案？我看只能在单机下使用
`
/**
 * 只适合单机适用
 *
 * @author mac
 */
@Component
@RefreshScope
public class Context extends SecurityContextHolder {

    private static final Logger log = LoggerFactory.getLogger("[Context]");
    private static final Map<Class<?>, Object> CONTENTS_MAP = new ConcurrentReferenceHashMap<>(16, ConcurrentReferenceHashMap.ReferenceType.WEAK);
    private static SecurityProperties securityProperties;
    private static RemoteUserService remoteUserService;
`

2、可以考虑下升级到最新的Spring Authoritarian Server吗？jwt工具类里面好多方法升级后都过时了

**Comment by 0x676e67** [comment]
1. Context只在认证服务器认证时候用到，临时保存在内存的，登陆认证信息是存在数据库中，集群也可以使用。
2. Spring Authoritarian Server可以自己fork项目一份升级版本号，在项目根目录gradle.properties中AuthorizationServerVersion字段

**Comment by 0x676e67** [comment]
刚才升级版本了，自己去看一下吧

**Comment by meimosor** [comment]
好的，非常感谢
